// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 23 Aug 2018 00:00:19 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package leopard

/*
#include "leopard.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Leo_init_ function as declared in leopard-go/leopard.h:105
func Leo_init_(Version int32) int32 {
	cVersion, _ := (C.int)(Version), cgoAllocsUnknown
	__ret := C.leo_init_(cVersion)
	__v := (int32)(__ret)
	return __v
}

// Leo_result_string function as declared in leopard-go/leopard.h:127
func Leo_result_string(Result LeopardResult) string {
	cResult, _ := (C.LeopardResult)(Result), cgoAllocsUnknown
	__ret := C.leo_result_string(cResult)
	__v := packPCharString(__ret)
	return __v
}

// Leo_encode_work_count function as declared in leopard-go/leopard.h:143
func Leo_encode_work_count(Original_count uint32, Recovery_count uint32) uint32 {
	cOriginal_count, _ := (C.uint)(Original_count), cgoAllocsUnknown
	cRecovery_count, _ := (C.uint)(Recovery_count), cgoAllocsUnknown
	__ret := C.leo_encode_work_count(cOriginal_count, cRecovery_count)
	__v := (uint32)(__ret)
	return __v
}

// Leo_encode function as declared in leopard-go/leopard.h:180
func Leo_encode(Buffer_bytes uint, Original_count uint32, Recovery_count uint32, Work_count uint32, Original_data []unsafe.Pointer, Work_data []unsafe.Pointer) LeopardResult {
	cBuffer_bytes, _ := (C.uint64_t)(Buffer_bytes), cgoAllocsUnknown
	cOriginal_count, _ := (C.uint)(Original_count), cgoAllocsUnknown
	cRecovery_count, _ := (C.uint)(Recovery_count), cgoAllocsUnknown
	cWork_count, _ := (C.uint)(Work_count), cgoAllocsUnknown
	cOriginal_data, _ := (*unsafe.Pointer)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Original_data)).Data)), cgoAllocsUnknown
	cWork_data, _ := (*unsafe.Pointer)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Work_data)).Data)), cgoAllocsUnknown
	__ret := C.leo_encode(cBuffer_bytes, cOriginal_count, cRecovery_count, cWork_count, cOriginal_data, cWork_data)
	__v := (LeopardResult)(__ret)
	return __v
}

// Leo_decode_work_count function as declared in leopard-go/leopard.h:202
func Leo_decode_work_count(Original_count uint32, Recovery_count uint32) uint32 {
	cOriginal_count, _ := (C.uint)(Original_count), cgoAllocsUnknown
	cRecovery_count, _ := (C.uint)(Recovery_count), cgoAllocsUnknown
	__ret := C.leo_decode_work_count(cOriginal_count, cRecovery_count)
	__v := (uint32)(__ret)
	return __v
}

// Leo_decode function as declared in leopard-go/leopard.h:227
func Leo_decode(Buffer_bytes uint, Original_count uint32, Recovery_count uint32, Work_count uint32, Original_data []unsafe.Pointer, Recovery_data []unsafe.Pointer, Work_data []unsafe.Pointer) LeopardResult {
	cBuffer_bytes, _ := (C.uint64_t)(Buffer_bytes), cgoAllocsUnknown
	cOriginal_count, _ := (C.uint)(Original_count), cgoAllocsUnknown
	cRecovery_count, _ := (C.uint)(Recovery_count), cgoAllocsUnknown
	cWork_count, _ := (C.uint)(Work_count), cgoAllocsUnknown
	cOriginal_data, _ := (*unsafe.Pointer)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Original_data)).Data)), cgoAllocsUnknown
	cRecovery_data, _ := (*unsafe.Pointer)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Recovery_data)).Data)), cgoAllocsUnknown
	cWork_data, _ := (*unsafe.Pointer)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Work_data)).Data)), cgoAllocsUnknown
	__ret := C.leo_decode(cBuffer_bytes, cOriginal_count, cRecovery_count, cWork_count, cOriginal_data, cRecovery_data, cWork_data)
	__v := (LeopardResult)(__ret)
	return __v
}
