// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 23 Aug 2018 13:06:06 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package leopard provides Go bindings for the leopard Reed-Solomon C++ library
*/
package leopard
